<?php
/**
 * @var $viewModel \Buhmann\Catalog\ViewModel\LayeredNavigation
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 * @var $escaper \Magento\Framework\Escaper
 */
$viewModel = $block->getData('viewModel');
?>
<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <div class="block-title filter-title">
            <strong><?= $escaper->escapeHtml(__('Shop By')) ?></strong>
        </div>

        <div id="layered-filter-block-content" class="block-content filter-content" data-bind="scope: 'layeredNavigation'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "#layered-filter-block-content": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "layeredNavigation": {
                            "component": "Buhmann_CatalogSmile/js/layered-navigation",
                            "accordionConfig": {
                                "openedState": "active",
                                "collapsible": true,
                                "active": <?= $block->getData('active') ?: 'false' ?>,
                                "multipleCollapsible": <?= !$viewModel->isMultipleCollapsible() ? "false" : "true" ?>
                            }
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
